---

- name: rsyslog | packages
  tags:
    - package
  package:
    name: "{{ item }}"
  with_items:
  - rsyslog
  - rsyslog-relp

- name: rsyslog | config
  tags:
    - config
  template:
    src: "{{ rsyslog_server_group in group_names | ternary('server', 'rsyslog') }}.conf.j2"
    dest: /etc/rsyslog.conf
  notify: restart rsyslog

- name: rsyslog | logrotate config
  tags:
    - log
  template:
    src: logrotate.j2
    dest: /etc/logrotate.d/rsyslog

- name: rsyslog | service
  tags:
  - service
  service:
    name: rsyslog
    state: started
    enabled: yes
